### ISSUE TITLE
Add code-quality checks to CI

### ISSUE THREAD

**Issue by Razvan00Rusu** [SOMAS2022/SOMAS2022#63]
Consolidating 3 existing code-quality issues (#30, #34, #47) into this one.

- [x] Add GolangCI-Lint to CI as  check.
> Will enforce better pre-merge checks for code quality.
- [x] <del> Automatic code quality tracking </del> (Implemented with golangci-lint)
> https://github.com/marketplace/actions/go-report-card
  https://github.com/creekorful/goreportcard-action
  Tracking code quality for every change, easily implemented with GitHub actions (second link has a complete implementation).
- [x] Add front-end & back-end eslint to CI (not super-necessary)
> Both the front-end and back-end have been configured with eslint configs. It would be great if these could be added to CI to ensure code quality in these projects.

**Comment by 0x6770** [comment]
@antonypap oh I didn't realise you have #48 WIP, will close my dev branch. The failed lint workflow can be fixed by adding `working-directory: pkg/infra` in its `yaml` file.

**Comment by antonypap** [comment]
> @antonypap oh I didn't realise you have #48 WIP, will close my dev branch. The failed lint workflow can be fixed by adding `working-directory: pkg/infra` in its `yaml` file.

Oh cool, yeah it's something we have worked with @Noanan. Feel free to pull and make changes

**Comment by 0x6770** [comment]
https://github.com/marketplace/actions/go-report-card

This GitHub action cannot be used in our repo because it's only a wrapper for this [website](https://github.com/creekorful/goreportcard-action), and it seems only check go entry file in root. 

Good news is most of the checks involved in `goreportcard` can be achieved by `golangci-lint` and `go vet`.

Therefore the planned `goreportcard` action is replaced by those two.
